[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "abc_sampling"
version = "0.1.0"
description = "Package for ABC Rejection sampling methods."
authors = [
    { name = "Rayen, Alaa, Amadou" }
]

dependencies = [
    "numpy",
    "scipy",
    "matplotlib", 
    "tqdm"
]